#ifndef CORUJA_ANSI_H
#define CORUJA_ANSI_H

// Common ANSI codes
#define CORUJA_ANSI_ESC_CODE "\x1b"
#define CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_ESC_CODE "["
#define CORUJA_ANSI_SEP ";"

// ANSI graphics codes
#define CORUJA_ANSI_GFX_SUFFIX      "m"
#define CORUJA_ANSI_GFX_RESET_CODE  "0"
#define CORUJA_ANSI_GFX_BOLD_CODE   "1"

// ANSI foreground standard color graphics codes
#define CORUJA_ANSI_GFX_FG_BLACK_CODE      "30"
#define CORUJA_ANSI_GFX_FG_RED_CODE        "31"
#define CORUJA_ANSI_GFX_FG_GREEN_CODE      "32"
#define CORUJA_ANSI_GFX_FG_YELLOW_CODE     "33"
#define CORUJA_ANSI_GFX_FG_BLUE_CODE       "34"
#define CORUJA_ANSI_GFX_FG_MAGENTA_CODE    "35"
#define CORUJA_ANSI_GFX_FG_CYAN_CODE       "36"
#define CORUJA_ANSI_GFX_FG_WHITE_CODE      "37"

// ANSI background standard color graphics codes
#define CORUJA_ANSI_GFX_BG_BLACK_CODE      "40"
#define CORUJA_ANSI_GFX_BG_RED_CODE        "41"
#define CORUJA_ANSI_GFX_BG_GREEN_CODE      "42"
#define CORUJA_ANSI_GFX_BG_YELLOW_CODE     "43"
#define CORUJA_ANSI_GFX_BG_BLUE_CODE       "44"
#define CORUJA_ANSI_GFX_BG_MAGENTA_CODE    "45"
#define CORUJA_ANSI_GFX_BG_CYAN_CODE       "46"
#define CORUJA_ANSI_GFX_BG_WHITE_CODE      "47"

// ANSI foreground bright color graphics codes
#define CORUJA_ANSI_GFX_FG_BRIGHT_BLACK_CODE      "90"
#define CORUJA_ANSI_GFX_FG_BRIGHT_RED_CODE        "91"
#define CORUJA_ANSI_GFX_FG_BRIGHT_GREEN_CODE      "92"
#define CORUJA_ANSI_GFX_FG_BRIGHT_YELLOW_CODE     "93"
#define CORUJA_ANSI_GFX_FG_BRIGHT_BLUE_CODE       "94"
#define CORUJA_ANSI_GFX_FG_BRIGHT_MAGENTA_CODE    "95"
#define CORUJA_ANSI_GFX_FG_BRIGHT_CYAN_CODE       "96"
#define CORUJA_ANSI_GFX_FG_BRIGHT_WHITE_CODE      "97"

// ANSI background bright color graphics codes
#define CORUJA_ANSI_GFX_BG_BRIGHT_BLACK_CODE      "100"
#define CORUJA_ANSI_GFX_BG_BRIGHT_RED_CODE        "101"
#define CORUJA_ANSI_GFX_BG_BRIGHT_GREEN_CODE      "102"
#define CORUJA_ANSI_GFX_BG_BRIGHT_YELLOW_CODE     "103"
#define CORUJA_ANSI_GFX_BG_BRIGHT_BLUE_CODE       "104"
#define CORUJA_ANSI_GFX_BG_BRIGHT_MAGENTA_CODE    "105"
#define CORUJA_ANSI_GFX_BG_BRIGHT_CYAN_CODE       "106"
#define CORUJA_ANSI_GFX_BG_BRIGHT_WHITE_CODE      "107"

#define CORUJA_ANSI_GFX_RESET CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_RESET_CODE CORUJA_ANSI_GFX_SUFFIX

#define CORUJA_BLACK_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BLACK_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_RED_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_RED_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_GREEN_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_GREEN_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_YELLOW_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_YELLOW_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BLUE_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BLUE_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_MAGENTA_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_MAGENTA_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_CYAN_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_CYAN_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_WHITE_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_WHITE_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX

#define CORUJA_BRIGHT_BLACK_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_BLACK_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_RED_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_RED_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_GREEN_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_GREEN_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_YELLOW_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_YELLOW_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_BLUE_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_BLUE_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_MAGENTA_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_MAGENTA_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_CYAN_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_CYAN_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX
#define CORUJA_BRIGHT_WHITE_BOLD CORUJA_ANSI_ESC_PREFIX CORUJA_ANSI_GFX_FG_BRIGHT_WHITE_CODE CORUJA_ANSI_SEP CORUJA_ANSI_GFX_BOLD_CODE CORUJA_ANSI_GFX_SUFFIX

#endif
